# Generated by Django 3.2.5 on 2021-08-21 10:02

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Content')),
                ('published_date', models.DateTimeField(auto_now_add=True, verbose_name='Publish Date')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('number_like', models.IntegerField(default=0, editable=False)),
                ('number_share', models.IntegerField(default=0, editable=False)),
                ('slug', models.SlugField(editable=False, max_length=265, unique=True)),
            ],
            options={
                'ordering': ['-published_date', 'id'],
            },
        ),
    ]
