# Generated by Django 3.2.5 on 2021-08-08 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_alter_post_published_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='number_like',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='post',
            name='number_share',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
