# Generated by Django 3.2.5 on 2021-08-05 18:44

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeAreas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('desc', ckeditor.fields.RichTextField(verbose_name='Desciption')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('surname', models.CharField(max_length=255, verbose_name='Surname')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Desciption')),
                ('faculty', models.CharField(max_length=255, verbose_name='Faculty')),
                ('graduated_date', models.DateField(verbose_name='Graduated Date')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('slug', models.SlugField(editable=False, max_length=265, unique=True)),
                ('areas', models.ManyToManyField(to='employee.PracticeAreas')),
            ],
        ),
    ]
