# Generated by Django 3.2.5 on 2021-08-21 10:02

import ckeditor.fields
from django.db import migrations, models
import employee.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Certificate Title')),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='PracticeAreas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', employee.models.UpperCaseField(max_length=255)),
                ('desc', ckeditor.fields.RichTextField(verbose_name='Desciption')),
                ('slug', models.SlugField(editable=False, max_length=265, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Practice Areas',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('surname', models.CharField(max_length=255, verbose_name='Surname')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Description')),
                ('faculty', models.CharField(max_length=255, verbose_name='Faculty')),
                ('graduated_date', models.DateField(verbose_name='Graduated Date')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name="Employee's Photo")),
                ('slug', models.SlugField(editable=False, max_length=265, unique=True)),
                ('areas', models.ManyToManyField(to='employee.PracticeAreas', verbose_name='Practice Areas')),
                ('certificates', models.ManyToManyField(to='employee.Certificate', verbose_name="Employee's Certificates")),
            ],
        ),
    ]
