# Generated by Django 3.2.5 on 2021-08-05 20:01

from django.db import migrations
import employee.models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='practiceareas',
            options={'verbose_name_plural': 'Practice Areas'},
        ),
        migrations.AlterField(
            model_name='practiceareas',
            name='title',
            field=employee.models.UpperCaseField(max_length=255),
        ),
    ]
