# Generated by Django 3.2.5 on 2021-08-05 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20210805_2301'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Certificate Title')),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='areas',
            field=models.ManyToManyField(to='employee.PracticeAreas', verbose_name='Practice Areas'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name="Employee's Photo"),
        ),
        migrations.AddField(
            model_name='employee',
            name='certificates',
            field=models.ManyToManyField(to='employee.Certificate', verbose_name="Employee's Certificates"),
        ),
    ]
