# Generated by Django 3.2.5 on 2021-08-14 10:10

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_auto_20210805_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='Description'),
        ),
    ]
