# Generated by Django 3.2.5 on 2021-08-21 10:02

import ckeditor.fields
from django.db import migrations, models
import employee.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faqs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', employee.models.UpperCaseField(max_length=255)),
                ('desc', ckeditor.fields.RichTextField(verbose_name='Desciption')),
            ],
            options={
                'verbose_name_plural': 'Faqs',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Ad')),
                ('phone_number', models.CharField(max_length=120, verbose_name='Telefon')),
                ('email', models.EmailField(default=None, max_length=254, verbose_name='Email')),
                ('subject', models.TextField(verbose_name='Mesaj')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GeneralSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Logo')),
                ('number', models.CharField(max_length=120, verbose_name='Telefon')),
                ('address', models.CharField(max_length=255, verbose_name='Adres')),
                ('email', models.EmailField(default=None, max_length=254, verbose_name='Email')),
                ('about', ckeditor.fields.RichTextField(verbose_name='AboutUs')),
                ('certificates', models.ManyToManyField(blank=True, null=True, to='employee.Certificate', verbose_name="Office's Certificates")),
            ],
            options={
                'verbose_name_plural': 'Settings',
            },
        ),
    ]
