# Generated by Django 3.2.5 on 2021-08-01 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Ad')),
                ('phone_number', models.CharField(max_length=120, verbose_name='Telefon')),
                ('email', models.EmailField(default=None, max_length=254, verbose_name='Email')),
                ('subject', models.TextField(verbose_name='Mesaj')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
