# Generated by Django 3.2.5 on 2021-07-31 11:54

from django.db import migrations, models
import django.utils.timezone



class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AddField(
            model_name='message',
            name='phone_number',
            field=models.CharField(max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='subject',
            field=models.TextField(default='sdada'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='name',
            field=models.CharField(max_length=120),
        ),
    ]
