# Generated by Django 3.2.5 on 2021-08-07 10:17

import ckeditor.fields
from django.db import migrations, models
import employee.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faqs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', employee.models.UpperCaseField(max_length=255)),
                ('desc', ckeditor.fields.RichTextField(verbose_name='Desciption')),
            ],
        ),
    ]
