# Generated by Django 3.2.5 on 2021-08-07 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_faqs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faqs',
            options={'verbose_name_plural': 'Faqs'},
        ),
    ]
