# Generated by Django 3.2.5 on 2021-07-31 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210731_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='email',
            field=models.EmailField(default=None, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='message',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Ad'),
        ),
        migrations.AlterField(
            model_name='message',
            name='phone_number',
            field=models.CharField(max_length=120, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='message',
            name='subject',
            field=models.TextField(verbose_name='Mesaj'),
        ),
    ]
