# Generated by Django 3.2.5 on 2021-08-14 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_alter_employee_description'),
        ('main', '0004_generalsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalsettings',
            name='certificates',
            field=models.ManyToManyField(blank=True, null=True, to='employee.Certificate', verbose_name="Office's Certificates"),
        ),
    ]
